### ISSUE TITLE
Nội dung cv không hiện ở cột 

### ISSUE THREAD

**Issue by giaays** [duxonem/Quick-Translator-in-one-file-html#1]
Mình đã thử paste chữ Trung vào cột Trung, sau khi bấm vào chỗ bất kỳ thì không có hiện tượng gì xảy ra. Đã thử dùng với data mặc định và data mình tải lên nhưng vẫn vậy. 
Link thử cuối readme hình như cũng bị lỗi, giao diện khác với video.

**Comment by duxonem** [comment]
Chào bạn, 
Đây chỉ là 1 file html và script js để convert vietphrase. Nó chưa bao gồm các file PhienAm, Names, Vietphrase bạn phải tải lên cho nó thì nó mới hoạt động chính xác được. Trường hợp bạn dán text Trung vào nhưng không convert là do bạn chưa tải các file trên vào chương trình.
Link cuối là để dùng thử nên không muổn tải file về. Đương nhiên nó cũng chỉ là file html như ở đây nên bạn phải tải các file PhienAm, Names, Vietphrase vào cho chương trình chạy. Tuy nhiên do chạy trên host nên trong phần giới thiệu của file đó mình đã để sãn link cho nó tự tải mấy file trên từ host luôn.

**Comment by giaays** [comment]
Mình hiểu ý bạn. Nhưng như mình có nói thì mình đã up data lên và dùng thử data sẵn bên trong nhưng đều không được. Gửi bạn [video](https://drive.google.com/file/d/1DJlSdDNn7YkFi4yeHLnm-YWs9xm3TXto/view?usp=sharing) mình sử dụng với data mình tải lên.

**Comment by duxonem** [comment]
Nếu được thì bạn cho mình xin mấy file data của bạn. Hôm trước cũng có 1 bạn hỏi giống vậy, nói lấy data ở đây và cũng chạy không được, cuối cùng kiểm ra file Names.txt chưa chuẩn. https://drive.google.com/drive/u/0/folders/0B6fxcJ5qbXgkeTJNTFJJS3lmc3c?resourcekey=0-Ych2OUVug3pkLgCIlzvcuA

Ngoài ra mình xem clip của bạn thấy giao diện cũ, lúc đó những file dữ liệu mình cho lưu vào localStorage của trình duyệt nên bị giới hạn 5MB, hiện đã cho chuyển qua IndexedDb của trình duyệt không bị hạn chế kích thước. Bạn thử tải lại html xem thế nào.

**Comment by duxonem** [comment]
Nó có lỗi ở file Names.txt đó bạn. Mình thay file khác chạy bình thường, không treo. Còn bị chỗ nào thì hôm bữa mình có coi rồi, giờ làm biếng kiếm lại. Với mấy file này dữ liệu rác, dư, ... quá nhiều.

Theo quan điểm mình thì file Name không cần để nhiều, truyện nào có danh sách tên của truyện đó, qua truyện khác là không dùng đến. Cho nên file Name của mình chỉ để tên tiếng Anh thôi.

**Comment by giaays** [comment]
Mình đã thử đổi file data khác, bao gồm cả data gốc bên TTV với kích thước dưới 5mb mỗi file thì vẫn không chạy được. Đều gặp lỗi Trang không phản hồi.

**Comment by duxonem** [comment]
Trong file Names.txt bạn gửi dòng 152722 nó bị lỗi, thay vì 
ABCD=【 Điểu 】 chi nhiệm vụ

Thì nó lại là 
=【 Điểu 】 chi nhiệm vụ

dẫn đến chương trình chạy lặp vô tận. Bạn có thể copy đoạn trên tìm thử trong file dữ liệu khác của bạn xem có không. 

Để mai mình rảnh sửa lại 1 chút nó sẽ không thêm chỗ dư liệu bị như này vào nữa

**Comment by duxonem** [comment]
Đã chỉnh lại, bạn tải file mới về dùng xem còn bị không

**Comment by giaays** [comment]
Mình đã chạy được file mới, cảm ơn bạn nhiều. Tuy nhiên mình gặp một lỗi khác là khi dùng chức năng VP một nghĩa thì chữ ở cột VP bị lỗi (cột phiên âm vẫn bình thường).
Khi bật VP 1 nghĩa:
![image](https://github.com/duxonem/Quick-Translator-in-one-file-html/assets/86505047/f8941b9d-3aec-4b0b-bcf3-ac1bee521a55)
Khi tắt lại bình thường
![image](https://github.com/duxonem/Quick-Translator-in-one-file-html/assets/86505047/1ddd1314-0caf-44a4-9ee2-5d406ccda184)

**Comment by duxonem** [comment]
Bạn tải lại thử nha. Chú ý khi chọn chỉ hiện 1 nghĩa thì bạn phải nhập dấu cách giữa các nghĩa vào ô bên dưới. Ví dụ trong các file các bạn dấu cách là /
Chương trình sẽ lấy nghĩa đầu tiên để hiển thị.

**Comment by giaays** [comment]
> Chú ý khi chọn chỉ hiện 1 nghĩa thì bạn phải nhập dấu cách giữa các nghĩa vào ô bên dưới.

Ô bên dưới là ô nào nhỉ, mình tải lại file vẫn vậy, không thấy ô nào để thêm dấu cả =(((

**Comment by duxonem** [comment]
![IMG_20230711_234713]
Bạn bấm chọn "Vietphrase một nghĩa" nó sẽ hiện ra ô để nhập. Nếu nó chọn sẵn mà không hiện thì bấm bỏ chọn rồi chọn lại
(https://github.com/duxonem/Quick-Translator-in-one-file-html/assets/128269506/d5022f0a-a5d7-410a-9f41-70382e99faff)

**Comment by giaays** [comment]
Ok rồi bạn ơi, cảm ơn bạn nhiều.
